- people.json
Update bio, excerpt, company, and YouTube information.
> Profile Updates

- people.json
The person was removed in https://github.com/cncf/toc/pull/343 and does not exist.
> Remove A Hobden

- people.json
Adding my Ambassador info : ) thanks!!
> Update my entry on the people file

- people.json
I'm pretty sure I'm done now. Thanks for the merges!
> I think I'm done

- people.json
Updated my profile a bit to align with my current status.
> Update Kasper Nissen bio

- people.json
Signed-off-by: OrlinVasilev <ovasilev@vmware.com>
> Update Orlin's excerpt

- people.json
Signed-off-by: OrlinVasilev <ovasilev@vmware.com>
> Update Orlin Vasilev

- people.json
- Adding language
- Adding projects
> Updating Chris Short

- people.json
Katie won the election for the TOC chosen seat: https://lists.cncf.io/g/cncf-toc/message/6787
> add Katie back to the TOC

- people.json
Hope it is OK that I still consider myself a TOC Contributor :-) Also some other small changes to reflect moving on from the TOC itself
> Update people file now I'm no longer TOC Chair

- people.json
We moved Liz (Prev Chair)  off in https://github.com/cncf/people/pull/56/files 
Adding me here as we forgot to do that in https://github.com/cncf/people/pull/66/files
Signed-off-by: Davanum Srinivas <davanum@gmail.com>
> Add dims to GB (TOC chair)

- people.json
Update profile and add pronouns and location.
> Update details for Noah Abrahams

- people.json
Update Brad McCoy's Location in people.json
Signed-off-by: Brad McCoy <bradmccoydev@gmail.com>
> update Brad McCoy's location

- people.json
Signed-off-by: Davanum Srinivas <davanum@gmail.com>
> Update Cathy Zhang's Bio

- people.json
Signed-off-by: Abubakar Siddiq Ango <h4xx22live@gmail.com>
> Update Abubakar's bio

- people.json
Updated bio, image, links
Signed-off-by: Baruch Sadogursky <jbaruch@sadogursky.com>
> Baruch Sadogursky update

- README.md
- people.json
Please see https://github.com/cncf/toc/issues/867 for context
Signed-off-by: Davanum Srinivas <davanum@gmail.com>
> Cleaning up "TOC Contributors" list

- people.json
Signed-off-by: Tom Kerkhove <kerkhove.tom@gmail.com>
> feat: Add location of Tom Kerkhove

- people.json
Signed-off-by: Davanum Srinivas <davanum@gmail.com>
> Change affiliation for Dims

- people.json
Annotell has rebranded into Kognic. Update to match
> Updating company name for Jessica 

- people.json
> fix missing punctuation

- people.json
Signed-off-by: Chris Abraham <cjyabraham@gmail.com>
> Test PR to test new sync

- people.json
Signed-off-by: Chris Abraham <cjyabraham@gmail.com>
> test update

- Makefile
- people.json
- schema.json
Noticed that the schema was blank but we have a fancy validator check. So I wrote a schema for it.
A few linkedin links weren't full URIs so I updated them.
I'm also sneaking in two new fields (for use with automation in the future) and populating my people entry with them so I can start work on that. 🙃
> Actually create a schema to validate against, update people.json with invalid urls

- people.json
- schema.json
Signed-off-by: Jeffrey Sica <me@jeefy.dev>
> change email format to match devstats

- config.yaml
- Remove folks who've left 
- Swap explicit permissions for team permissions re: devstats/landscape devs
> Permissions Scrub/Update

- people.json
> update MZ bio

- people.json
Updates bio to clarify that I'm the Kubernetes Rep and not specifically there on behalf of Red Hat.
> Update bio for Kubernetes Rep

- config.yaml
> add paulliwog to end users

- config.yaml
Signed-off-by: Greg Jacobs <68873331+gregjacobs-thrivent@users.noreply.github.com>
> Add self to end users team

- people.json
> Add Anne to GB

- config.yaml
Just adding a few of us for now -- happy to add more if it's useful later.
> Add key members from G-Research's OSPO

- config.yaml
> Add sfudeus and david-m-m for the end-user team

- config.yaml
Signed-off-by: Mattias Öhrn <mattias.ohrn.1@volvocars.com>
> Adding myself to GitHub End User team

- config.yaml
adding myself to the list of cncf-end-users
> add slevinwasalreadytaken to the cncf-end-users listing

- config.yaml
ref CNCFSD-1572
Signed-off-by: Robert Kielty <robert.kielty@cncf.io>
> Adds duglin to cncf/wg-serverless

- config.yaml
Signed-off-by: Robert Kielty <robert.kielty@cncf.io>
I've set admins to myself @onlydole and @jeefy
> adds sheriff repo, sets admins

- config.yaml
Signed-off-by: Amye Scavarda Perrin <amye@linuxfoundation.org>
> Adding TOC as of 2/8

- config.yaml
> add upsider to end user

- people.json
Signed-off-by: Amye Scavarda Perrin <amye@linuxfoundation.org>
> Removing emeritus TOC, adding new

- config.yaml
Signed-off-by: Taylor Dolezal <onlydole@gmail.com>
> Add Public Sector User Group

- config.yaml
- people.json
See https://github.com/cncf/tag-security/pull/1033 for related approvals
> Add John Kjell for external collaborator to TAG Security

- config.yaml
Adding myself to maintain two CNCF open source WordPress plugins - one of which needs an [update](https://github.com/cncf/cncf.io/issues/660).
> Adding myself to maintain CNCF WordPress plugins

- config.yaml
correcting users in cncf/landscape. 
removing nate-double-u from cncf/students
> cncf/landscape cncf/students user update

- people.json
Please see https://github.com/cncf/toc/issues/1026
> Update people.json - Emily Fox as now TOC Chair represents TOC on CNCF GB

- config.yaml
- Add folks to an upcoming KubeCon + CloudNativeCon EU 23 Demo Repository.
- YAML linting cleaned up some spaces!
> Add folks to a KCCN EU 23 demo repo

- .github/workflows/enforce-pr-labels.yml
- Update syntax of GitHub Action job for checking PR labels.
> Update Enforce PR labels rule

- config.yaml
> Add devstats-landscape-sync

- config.yaml
* Add `TheMoxieFox` as a maintainer role
* Update `joannalee333` to an admin role
> Add Working Group CoC Collaborators

- config.yaml
Add the following folks: 
- [@nikimanoledaki](https://github.com/nikimanoledaki)
- [@caradelia](https://github.com/caradelia)
- [@catblade](https://github.com/catblade)
> Add TAG Env Sustainability folks

- README.md
> documents our use of sheriff to administer access to CNCF repos

- people.json
As per #205 & [cncf/cncf.io #731](https://github.com/cncf/cncf.io/issues/731)
> adding nate-double-u mastodon account

- config.yaml
<sub>Sean Schneeweiss <sean.schneeweiss@mercedes-benz.com>, Mercedes-Benz Tech Innovation GmbH, [Provider Information](https://github.com/mercedes-benz/foss/blob/master/PROVIDER_INFORMATION.md)</sub>
> Add seanschneeweiss to cncf-end-users

- people.json
Removing wechat id as it is not working.
> Update people.json Yongkang He

- config.yaml
- Update internal repositories visibility
- Rename Landscapers team to lowercase
- Update jberkus role to member
> Some adjustments in preparation for CLOWarden

- config.yaml
Removing old mentee, adding new mentee, adding Jorge C. to landscapers
/cc @castrojo
> Updating Landscape access

- config.yaml
* updating @avantikajain289's access to triage
* re-adding @Hilzygift as per @andreuxxxx's request
> updating cncf/landscape access

- config.yaml
Ref:
- [slack discussion](https://cloud-native.slack.com/archives/CPBE97SMU/p1687769092920189)
- https://github.com/cncf/tag-runtime/tree/main#members
cc @raravena80 @helayoty
> config: update TOC liaisons, chairs and TLs for tag-runtime

- config.yaml
> Configure access to new repo

- people.json
As per https://github.com/cncf/cncf.io/issues/754
> Add GB and TOC roles in dedicated fields

- config.yaml
Brandon --> Pushkar: 
Result: https://lists.cncf.io/g/cncf-toc/message/8173
Vote: https://lists.cncf.io/g/cncf-toc/topic/99287905
Jeyappragash Jeyakeerthi --> Brandon:
Result: https://lists.cncf.io/g/cncf-toc/message/5884
Vote: https://lists.cncf.io/g/cncf-toc/topic/83172695
> Update permissions for TAG Security Leads

- config.yaml
Adding @swil78 to cncf/mentoring
> Adding Swil78 to cncf/mentoring

- people.json
Updating my affiliation to reflect my new employer.
> Updating with new employer

- config.yaml
> Adding James to Tag Contributor Strategy repo

- config.yaml
Hello folks !
We hope to update the permission for the cncf/glossary repository based on..
https://github.com/cncf/glossary/pull/2370
> Update cncf/glossary external_collaborators

- config.yaml
* changes the permissions to the TAG App Delivery Repo according to the current structure
> feat: update tag app delivery permissions

- config.yaml
Carlos is going to help curate incoming presentations.
> Add Carlos Santana to cncf/presentations

- config.yaml
> chore: promote BobyMCbobs, hh & Riaankl to k8s-conformance admins

- people.json
Just a little profile update 🙂✨
> Add LinkedIn

- config.yaml
Hello folks !
We've recently added new localization approver (@tym83) to the cncf/glossary repository
- Based on https://github.com/cncf/glossary/pull/2577
We need to update config.yaml in cncf/people in order to follow the CNCF Sheriff bot.
> Add cncf/glossary external_collaborators

- people.json
Updated my location to Paris, France
> Andrea - moved to Paris, France

- people.json
> Sara Trappetti profile update

- config.yaml
Adding myself to Artwork repo to help maintain
> Add myself to Artwork repo

- config.yaml
https://lists.cncf.io/g/cncf-toc/message/8317
> TAG Security chair transition Aradhna -> Marina

- config.yaml
add working group chairs and TLs
> Update TAG ENV team

- config.yaml
Adds @cmierly as writer to the foundation repo
> grants cmierly write access to foundation

- config.yaml
Add @DPalilonis to the cncf-end-users team on GitHub.
> Add David Palilonis to the End User group

- people.json
> Update Taylor Dolezal's Bio

- people.json
Updating the weighting for the Staff page.
> Update weighting parameter

- config.yaml
Update End User team permissions.
> Allow End User Team to work in the End User private repo

- people.json
context: please see https://github.com/cncf/toc/pull/1259
> Add myself (dims) back as part of TOC

- people.json
1. add Kevin Wang as part to TOC per https://github.com/cncf/toc/pull/1249
2. also updated Kevin's bio
> add Kevin Wang to TOC

- config.yaml
> config.yaml: add users to cncf-end-users

- people.json
Updated bio for Alessandro Vozza
> chore: update alessandro affiliation

- config.yaml
- Alois stepped down as Chair
- Lian was voted in as Chair and confirmed by TOC
- GitOps WG merged with OpenGitOps
- Platforms WG elected a new chair
- Artifacts WG elected a new chair
@Riaankl
> Update TAG app delivery personell

- people.json
updated bio for chad crowell, as he is now working at Civo as a senior platform engineer.
> updated profile for chad crowell

- config.yaml
Erin has stepped down as of 05/01/2024
> Remove Erin from TOC group

- people.json
Spelled my country name in Danish. This PR corrects that
> Fix typo for Kim Sondrup

- people.json
Change my company information.
> chore: update Tiexin Guo's information in people.json

- config.yaml
> Add Picnic CNCF end-users

- people.json
Updated profile for Sander van Bruggen in people.json, changed country from "The Netherlands" to "Netherlands" so that my profile appears in the the geographically filtered list
> Updated profile Sander van Bruggen

- people.json
Update my profile (Christopher Adigun)
> Update My Kubestronaut Profile In people.json

- people.json
> Update my profile in people.json

- people.json
This is to update the linkedin handle from ```https://www.linkedin.com/in/www.linkedin.com/in/sajeeval``` to ```https://www.linkedin.com/in/sajeeval```
> update sajeeva's linkedin handle

- people.json
> Update people.json for Carlos Santana

- people.json
There was a typo in the location field of my data.
> updated Peter Dongo's location

- config.yaml
Update TAG ENV Sustainability group, see https://github.com/cncf/tag-env-sustainability/issues/421 & https://github.com/cncf/toc/issues/1322
> Add saiyam pathak to tag env sustainability group

- config.yaml
ref: https://github.com/cncf/tag-security/issues/1250
> TAG Security Co-Chair Transition: Andrew Martin -> Eddie Knight

- people.json
Add my company, LinkedIn page, website link, slack and wechat.
> Update profile for Roy Liang

- people.json
> Clearning skills and adding https on domain

- people.json
Updating the location to match the syntax of other entries after I noticed I wasn't listed properly on the Ambassador site. Adding company as well.
> Updating location information for Joe Searcy

- people.json
Hello! I am updating my profile info based on the docs at https://github.com/cncf/ambassadors/blob/main/2.0/Profile.md
> Update profile info for "Luca Cavallin"

- people.json
Just added a few details about myself to be reflected on the Ambassadors page :pray:
> Update Dmitry Shurupov as CNA

- people.json
Split Software was acquired by Harness. Updating my profile.
> Updating company for Pablo Fredrikson

- people.json
Change the company Netic A/S name to match the name used in The Linux Foundations EasyCLA system
> Change company "Netic" to "Netic A/S"

- people.json
correction in linkedin URL - Arun Avasare
> correction in linkedin URL - Arun Avasare

- people.json
Edit LI, HENGYUE info, change location and add github URL.
> Edit LI, HENGYUE info, change location

- people.json
**Profile details update** - @huats for your review and approval. Thank you!
> Update kubestronaut profile

- config.yaml
Adds additional TAB members to the cncf-tab team
> Add additional TAB members to cncf-tab team

- people.json
> Update bio and company for Patrick Easters

- people.json
> chore: updating the city name

- config.yaml
> feat: add heyste to k8s-conformance admins

- config.yaml
Add `robertglenn` as maintainer for cncf/cartografos, as coordinated with @onlydole
> Add robertglenn as maintainer for cncf/cartografos

- people.json
Remove unnecessary line breaks, add small adjustments to the bio of Maxim Skakun.
> Adjust bio of Maxim Skakun

- people.json
To resolve the issue of having 2 people with the same name
> Modify Daniel Dias name to include middle name

- people.json
* Updating Rodrigo Bersa's location from Chantilly, France to Chantilly, United States.
> fix: Update Rodrigo Bersa's location on `people.json`

- config.yaml
* Add @djmoch to the Public Sector End User Group repo
> Update Daniel Moch access to the Public Sector End User repo

- people.json
Updated BIO and Company name for Madhu Mallisetty - Kubestronaut profile.
> Updated people.json - Madhu Mallisetty

- config.yaml
* Add `menzenski` to the end user team
> Add menzenski to the End User team

- people.json
> Updated people profile

- people.json
Update my profile, add social network account handles and company
> Update Jimmy Song's profile

- people.json
update details for Dotan Horovits, CNCF Ambassador
> Update people.json - add bluesky details for Dotan Horovits

- people.json
> feat: updating the organization name

- people.json
Added LinkedIn, Bluesky, YouTube, Website and Languages
> Update people.json for Andreas Grabner

- people.json
Adding bluesky account, and remove twitter
> feat: update social media

- people.json
> update: change place of work in my kubestronaut profile

- people.json
Update location from Dubai, Dubai to Dubai, United Arab Emirates for user vishnu-kumar-sharma
> Update location from "Dubai, Dubai" to "Dubai, United Arab Emirates" 

- config.yaml
> Add maintainer summit repo

- config.yaml
Fixes: https://github.com/cncf/tag-contributor-strategy/issues/745
> Add TAG Contributor Strategy members to config.yaml

- people.json
Add `bluesky` handle for `rexagod`.
> Add `bluesky` handle

- people.json
> Add ChengHao's bluesky account

- people.json
> Add my Bluesky account

- people.json
Adding Bluesky & Slack ID, removing Twitter for my account.
> Add Bluesky to Dmitry Shurupov

- people.json
- Update my profile 
- `NA (Student at University of Tsukuba)` -> `University of Tsukuba`
> Update my profile (Okabe-Junya)

- people.json
- Removed a duplicate entry under my profile.
- Updated categories to reflect the correct ones I belong to.
- Changed country information to match my current location.
These changes ensure accuracy and eliminate redundancy in the data.
> Remove Duplicate Entry and Update Personal Information

- people.json
Corrected Daiki Hayakawa's location.
> Fix Daiki Hayakawa location

- people.json
Update location for Oleg Lipovchenko
> Update Oleg Lipovchenko info

- people.json
Changing the organization name.
> feat: changing the organization name

- people.json
Some updates to my bio. Thank you.
> Update jkowall info on the ambassador page

- people.json
Hi, I'm updating company name in my kubestronaut page
> fix: update company name in kubestronaut profile

- people.json
Update website URL for Sajeeva Nambadawa Vithanage
> Update website URL for Sajeeva Nambadawa Vithanage

- config.yaml
  @juliasimon - canceled her invitation
  @kumarankit999 - non-existent user
> Fix CLOWarden warnings

- people.json
This PR contains more details about my social media and language skills.
> Update details for Gerald Venzl

- people.json
Making two small updated to my personal info:
1. Add bluesky profile
2. Update company to University of Toronto
3. Unset twitter url (I don't have an account there, not sure how a default url got added to my profile)
> Updated info for Calum Murray

- people.json
Update details of Sander Sneekes
> Update details of Sander Sneekes

- people.json
Updated my own entry in people.json to match with my current employer.
> Updated company for my entry in people.json

- people.json
Updated the bio to reflect the current role.
> Update people.json to reflect Sreejith's bio.

- people.json
Hi! I've recently changed company and wanted to reflect the change here also 😄
> Update people.json - changed company sbruzzese902

- people.json
> Update location value for Arnaud Tron

- .github/workflows/enforce-pr-labels.yml
- .github/workflows/validate.yml
Fixes #817
Signed-off-by: Ihor Dvoretskyi <ihor@linux.com>
> Update GitHub Actions workflows to use self-hosted runners

- people.json
Update personal website from mark.wilson.codes to mark.codes
> Update website in people.json

- people.json
> typo in name.

- .github/workflows/validate.yml
as per description, runner is currently offline, but this should bring it up.
> reinstates equinix-2cpu-8gb

- people.json
Updated bio and social links as per Katies instructions.
> Kevin Evans bio update and social links.

- people.json
Sorry, adding a few more changes here.
> Make some changes to my profile

- people.json
Adding certdirectory.io profile
> feat: adding certdirectory.io profile

- people.json
Adding website and certdirectory urls for Sergio Canales (me)
> Sergio Canales website and certdirectory updates

- people.json
* Remove myself as CNCF Staff
* Update company
> Update Taylor Dolezal's profile details

- people.json
Updated Abhimanyu bajaj's country in people.json
> Updated Abhimanyu Bajaj's country in people.json

- people.json
fix: correct name Elyes Jarroudi
> fix: correct name Elyes Jarroudi

- people.json
Added CertDirectory link for listing - Raja Ravindra Kathi
> Added CertDirectory link for Raja Ravindra Kathi

- people.json
I corrected my slack id to get access to the private kubestronaut channel.
> Update slack id of Stathis Kapaniaris's profile

- people.json
Update bio and main website link for Kristina Devochko in `people.json`
> Update information for Kristina Devochko in people.json

- people.json
Change bio and company for Mark Højer Hansen (me)
> Changed Mark Højer Hansen company

- people.json
Update the profile for @windsonsea
> Update windsonsea profile in people.json

- people.json
Update my location to Rochester, Minnesota instead of Rochester, New York.
> Update my location

- people.json
This pull request includes updates to the `people.json` file to add additional social media links for a user.
Social media links added:
* Added LinkedIn profile link for the user.
* Added YouTube channel link for the user.
> Update Ahmed Bebars Profile

- config.yaml
https://github.com/cncf/tag-contributor-strategy/pull/779
> Add sandeepkanabar to replace Deafveloper

- people.json
> Add Chad to people.json

- people.json
- Removes previous members
- Adds new members
- Update's role for Kevin
> Update TOC member's people information

- people.json
Signed-off-by: Chris Abraham <cjyabraham@gmail.com>
> update people.json location + name WassimRegaieg

- config.yaml
- Add @sfb103 to the Public Sector End User Group repo
> Update Sean Bentley access to the Public Sector End User repo

- people.json
This PR Updates my affiliation to the new role I have.
> Update Mohammad Reza Affiliation

- config.yaml
Updating @alexcontini's access to cncf/artwork after we added branch protections.
> udpating user access for cncf/artwork

- people.json
hi folks!
I'm updating my personal data, since I moved to another city and changed my job.
> chore: update daniel dias info

- people.json
adding certdirectory profile reference for kubestronauts
> adding certdirectory reference

- people.json
Change the company information for Sajeeva
> change the company information - Sajeeva

- config.yaml
ref. https://github.com/cncf/glossary/issues/3431
I (@Okabe-Junya) have joined the glossary maintainer team, so let me update my permission
> Update my permission in cncf/glossary

- people.json
Hi!
There is a small typo in the province name, also - has to be removed from the company name.
Is it possible to correct this?
Many thanks,
René
> Correct typo's

- config.yaml
> add koksay/mfahlandt to automation repo

- people.json
I remove the double registry about me ...
> Remove Double Registry of Chamo

- people.json
> Fix Location City of Chamo

- config.yaml
Hi!
we are promoting some collaborators of the glossary Italian localization team, while someone is stepping out (see https://github.com/cncf/glossary/pull/3449). Therefore we need these changes
> update dev-it approvers

- config.yaml
Related to https://github.com/cncf/glossary/pull/3455
> Remove edsoncelio from cncf/glossary localization

- config.yaml
/cc @seokho-son, @iamNoah1, @jihoon-seo, @Okabe-Junya
> adding hlipsig to the cncf glossary repo as write

- config.yaml
ref. https://github.com/cncf/glossary/issues/3458
- Add @ntheanh201 @thuanpham582002 to cncf/glossary external collaborator
> Initialize CNCF Glossary Vietnamese Localization Team

- people.json
Hello,
excuse me, the Linkedin URL seems to be broken in my JSON object. This should fix it
Best regards,
> fix: update linkedin url

- people.json
> Update Jooho Lee's profile in people.json

- people.json
I have changed my position, my employer, and my location.
> change employer and location

- config.yaml
reference: #974
- Add @thaomike to vi l10n reviewer
> Update CNCF Glossary Vietnamese Localization Team

- people.json
added https://b1-systems.de to kubestronaut matthias brodbeck
> added website to matthias brodbeck

- people.json
Update company and social links
> Update company and social links

- people.json
Hello,
I would like to make some changes on my Kubestronaut profile - Mateusz Romaniuk (changes in the company, bio, GitHub and Slack ID)
I asked about this via mail. In a minute, I will ping you on the Slack :)
Thanks,
Mateusz Romaniuk
> add changes to mateusz-romaniuk-profile

- config.yaml
Add access to conformance for the people discussed in the meeting 8th may 2025
> Add access to conformance

- people.json
> chore: update profile

- people.json
This pull request updates my company affiliation in the CNCF people repository to reflect my current employer. No other changes are introduced.
> Update company affiliation for Shushanth Sanjay Kumar

- people.json
> Update company name

- people.json
> Update dims employer affiliation

- config.yaml
cc @riaankleinhans @mrbobbytables
> fix tag workloads display name

- config.yaml
Related to [PR](https://github.com/cncf/glossary/pull/3546)
> Remove aj11anuj from cncf/glossary localization

- people.json
Adding Cert Directory Reference for Kubestronauts & Golden-Kubestronauts
Review Done by: Sajeeva Nambadawa Vithanage
> Adding Cert Directory Reference

- people.json
update my profile "Yilmaz Guleryuz"
> update my profile "Yilmaz Guleryuz"

- people.json
Change company name in profile description
> update company for user - Marius Matonis 

- people.json
Update main information about Damian Sztankowski in ` people.json`
> chore: Update main information about Damian Sztankowski in people.json

- people.json
update company info from Carrier to LexisNexis
> update company because I found a new job 

- people.json
- Added Slack link to profile
- Included CertDirectory details
- Updated with Golden Kubestronaut title
> update(profile): add Slack, CertDirectory, and Golden Kubestronaut title to Ivan Totev profile

- config.yaml
See if commit is signed off...
> Add Andrew as Admin
