- people.json
Signed-off-by: Taylor Dolezal <onlydole@gmail.com>
Remove Eli May as he no longer works for the CNCF.
> Remove Eli May

- .github/workflows/validate.yml
- .vscode/settings.json
- README.md
With [Sheriff](https://github.com/electronjs/sheriff) eventually helping us manage Slack and other tooling, we need to rally around a repo that has things like user data and team configs. So this PR adds docs on what new fields exit (`slack_id` and `email`) ~and creates a PR check that runs Sheriff (as a dry-run!) to validate people.json/config.yaml changes.~
Due to limitations with GHA secret handling, we can't actually do a PR check 🙃 This is something to be worked on in the future, but for now we should get notified of a bad apply via Slack.
> Add config.yml PR Check, docs on additional fields

- config.yaml
Associate the End User GitHub team with the private GitHub repository.
> Add End User team to Private End User repo

- config.yaml
Hello folks !
We've recently added a new localization approver (@ramrodo) to the cncf/glossary repository
- Based on https://github.com/cncf/glossary/pull/1704
I guess we need to update config.yaml in cncf/people in order to follow the new CNCF Sheriff bot.
> Add `ramrodo` to cncf/glossary external_collaborators

- config.yaml
As a part of https://github.com/cncf/landscape/issues/2467, and the possibility of a Students WG under TAG Contributor Strategy:
* Adding Nate W. (@nate-double-u) to Landscape and Students repos as admin
* Adding Andrea V. (@andreuxxxx) to Landscape as triage
* Adding Hilda O. (@Hilzygift) to Landscape as read
/cc @caniszczyk @RobertKielty @jeefy
> Updating Landscape and Students repos

- config.yaml
cc @leonardpahlke @nate-double-u 
Creates 2 teams
- tag-env-sustainability
- cncf-tech-docs
Adds a new GitHub repo 
- tag-env-sustainability-website
Please review for correctness and completeness.
> Adds tag env sustainability website repo

- .github/workflows/dryrun.yml
Taking org from ${ github.event.repository.owner.name } for  PERMISSIONS_FILE_ORG as previous setting did not work
> Retrieves org name for PERMISSIONS_FILE_ORG

- .github/workflows/dryrun.yml
- config.yaml
I did not include maintainers on my last PR for cncf-tech-docs and this caused sheriff permission sync to not run to completion. (Now a GH Action here!)
This PR adds maintainers to the team.
> adds maintainers to cncf-tech-docs

- .github/workflows/dryrun.yml
Hard coding cncf as the org for PERMISSION_FILE_ORG for now
I really need to see Dry Run Action run to fix config.yaml team entries. 
This should help restore the cncf/sheriff to regular runs via GitHub Actions.
> hard codes cncf as the org being managed by cncf/sheriff

- config.yaml
Teams MUST have maintainers and members. Sheriff Dry Run action caught that problem.
> Fixes validation errors

- config.yaml
Pushed last config.yaml change to main in error with an error, this _should_ fix that.
This adds a cncf-automation team and repo.
> fixes cncf-automation

- config.yaml
Using instead cncf/tag-env-sustainability/tree/main/website
> removes tag-env-sustainability-webiste as not needed

- config.yaml
thetwopct (James Hunt) already had write access to contribute repo (now archived), this gives same permission on the merged tag-contributor-strategy repo
> Giving thetwopct write access to tag-contributor-strategy

- config.yaml
Hello folks !
We've recently added a new localization approver (@sestegra) to the cncf/glossary repository
- Based on https://github.com/cncf/glossary/pull/1976
We need to update config.yaml in cncf/people in order to follow the CNCF Sheriff bot.
> Add `sestegra` to cncf/glossary external_collaborators

- config.yaml
Hello folks !
We've recently added new localization approvers (@pichuang @ydFu) to the cncf/glossary repository
- Based on https://github.com/cncf/glossary/pull/2003
We need to update config.yaml in cncf/people in order to follow the CNCF Sheriff bot.
> Add cncf/glossary external_collaborators

- config.yaml
Hello folks !
We've recently updated permissions for the cncf/glossary repository (https://github.com/cncf/glossary/pull/2046)
1. Add initial approvers for Japanese Localization based on the initiation request (#1422)
Kohei Ota (@inductor)
Nao Nishijima(@naonishijima)
Kaito (@kaitoii11)
2. Change permission for @iamNoah1 @jihoon-seo from maintain to admin so that the maintainers can merge a PR related with branches 
3. Remove inactive localization approvers
We need to update config.yaml in cncf/people in order to follow the CNCF Sheriff bot.
> Update cncf/glossary external_collaborators

- config.yaml
This change brings cncf/people/config.yaml into line with the current [repo-local access perms in settings.xml](https://github.com/cncf/tag-contributor-strategy/blob/main/.github/settings.yml)
Once this change is reviewed merged and tested we can then remove the perms defines in settings.xml on repo.
Of note is my attempt to create teams based on the roles defined over on the TCS repo.
cc @jberkus @geekygirldawn @CathPag
> adds TAG Contributor Strategy Teams

- config.yaml
Adding @aliok and @Riannkl as admins for TAG-Contributor strategy.
Follow-ups: both will need to be invited to CNCF org.
@RobertKielty
> Add new Tech Leads for TAG-Contributor Strategy

- config.yaml
Hello folks !
We hope to update permission for the cncf/glossary repository.
1. Add @castrojo to the list of English approvers (external_collaborators with write permission in cncf/glossary) based on https://github.com/cncf/glossary/pull/2183
> Update cncf/glossary external_collaborators (add `castrojo`)

- config.yaml
Giving myself admin access to the project-template repo.
Confirmation that I should have this access can be found in this [issue](https://github.com/cncf/project-template/issues/42).
> Added permissions for the project-template repo. 

- config.yaml
As difficult as this is, I've finally removed Carolyn's access from the CNCF repos in case her GitHub account is compromised at some point in the future and so that she isn't the suggested reviewer for new PRs 😿
> As difficult as this is, I've finally removed Carolyn's access

- config.yaml
I'm in a new role focused on developer satisfaction so I'm looking to improve the `servicedesk` README and resolve/merge the outstanding PR.
> Add krook (CNCF staff) as a maintainer on the servicedesk repo.

- config.yaml
Adding Paul (@psgustafson) and Judy (@jbogarthyde) of Expert Support to cncf/techdocs repo.
> Updating cncf/techdocs repo access

- config.yaml
The TAG ENV recently launched the WG Green Reviews and selected @guidemetothemoon and @nikimanoledaki as WG Chairs. This PR adds the two working group chairs to the TAG ENV repo. 
ref issue: https://github.com/cncf/tag-env-sustainability/issues/186
cc @nate-double-u @RobertKielty
> Add wg green reviews chairs

- config.yaml
Adds @Cmierly to the cncf-projects team which in turn will grant Crystal the same repo access as @amye
> adds CMierly to the cncf-projects team

- config.yaml
Adding Chris Larsen @manolama and Vijay Samuel @vjsamuel to the Observability TAG repo as writers to help with the Observability Query Language Standards working group. See https://github.com/cncf/tag-observability/blob/main/working-groups/query-standardization.md
> Add Query Working Group Users to OBS TAG Repo

- config.yaml
>  #290: Updated config.yaml

- config.yaml
Adds CLOWarden access rules to cover new repo cncf/subdoamin-redirector
> Adds subdomain-redirector setup

- config.yaml
> Add riaankl to toc admin

- config.yaml
@taylorwaggoner, values must be valid GitHub usernames (case sensitive)
> Fix Cmierly access to k8s-conformance repo

- config.yaml
Signed-off-by: Antonio Di Turi anto.dituri@gmail.com
> request to add AntonioDiTuri to the members of the tag-env-sus

- config.yaml
Updates the TAG ENV team. Removes Cara as she is stepping down as TL and WG Chair for Comms. Antonio and Ross are added as WG Green Reviews Chair / TL. Claire and Savithara are added as WG Comms TLs.
> update TAG ENV team and add TAG ENV chairs team

- config.yaml
Update TAG Security collaborators according to https://github.com/cncf/tag-security/pull/1232
> Update tag-security collaborators

- config.yaml
This PR adds @Nancy-Chauhan to the TAG ENV GitHub group.
> Add nancy to TAG ENV list

- config.yaml
To be able to contribute and help manage initiatives for the CNAI working group, I was asked to add `write` permissions (cc @raravena80). For example, to be able to contribute to https://github.com/orgs/cncf/projects/38/views/1
> Add write permissions for zanetworker in tag-runtime

- config.yaml
Adding Marta and Jacob to the TAG Environmental Sustainability so they can execute their task for their project.
> Add new project leads to TAG Environmental Sustainability

- config.yaml
The account `bvera` does no longer exist on GitHub, so every time CLOWarden tries to set its permissions, an error is raised.
> Remove non-existent account from permissions file

- README.md
Suggestion that we add a link to the [Kubestronaut page](https://www.cncf.io/training/kubestronaut/) on cncf.io to the README.md
> Added link to Kubestronauts in README.md

- people.json
I changed my location from Türkiye to Turkey.
Globally Turkey country now recognise as Türkiye but on Kubestronaut page I can't see Türkiye location.
So I changed my location to Turkey.
> location fixed

- config.yaml
contributes to: https://github.com/cncf/techdocs/issues/232#issuecomment-2110716462
> Bumping chalin's access in cncf/techdocs

- people.json
Fixes the image link added in #512
> fix: use proper image for Nathanael Liechti kubestronaut

- config.yaml
It looks like user @wavell has changed their username to @wvwatson. This change hasn't been applied to the permissions file yet, so CLOWarden is [trying to add the user back over and over](https://clowarden.io/audit/?organization=cncf). This PR fixes this issue by updating all entries where this username was used.
/cc @jeefy
> Rename wavell to wvwatson

- config.yaml
* Removes @joshgav as Chair (https://github.com/cncf/tag-app-delivery/issues/696)
* Removes @angellk as a TL as she stepped up to the TOC
> doc: update TAG App Delivery Leadership

- config.yaml
Adds @nate-double-u as an admin to this repo.
I re-ordered the entries so that `name: people `appears before `external_collaborators`
> Adds Nate as an admin to cncf/people

- config.yaml
Removing hugo-netlify-starter repo as per https://github.com/cncf/hugo-netlify-starter/issues/113
> removing hugo-netlify-starter repo as it is being archived.

- config.yaml
- Adds `@Dindihub` as techdocs collaborator - LFX 24T2
- Drops `jbogarthyde`, who I believe is no longer working on the techdocs
cc @nate-double-u
> Add `@Dindihub` as techdocs collaborator - LFX 24T2

- config.yaml
Team members are currently the only ones that are a member of the CNCF org. 
It'll be updated later once the other members have accepted an org invite.
> Add team for end user TAB

- config.yaml
The private repo will be used as an extension of the toc private board so that items from the board can be converted to issue for further discussion and assignment.
> Create toc-private repo

- config.yaml
also adds the team to the sandbox repo so they can be assigned issues and update labels
> Add TAG leads team

- people.json
This PR fixes the incorrect LinkedIn URL in the people.json file for Vander Nunes.
The previous URL had an extra prefix, causing a broken link. This update corrects it to ensure the link is functional.
> fix: correct LinkedIn URL for Vander Nunes

- config.yaml
This PR updates the member list of TAG ENV
ref tracking issue: https://github.com/cncf/tag-env-sustainability/issues/531
ref issue max stepping down: https://github.com/cncf/tag-env-sustainability/pull/527
cc @riaankleinhans
> Remove max as chair from TAG ENV

- config.yaml
Adds Rajas (TL of TAG Runtime) to the access config of TAG Runtime
ref: https://github.com/cncf/tag-runtime/tree/main/README.md#tag-tech-leads
cc @raravena80
> Update list of TLs in TAG Runtime access config

- config.yaml
This PR updates the list of members in TAG Environmental Sustainability
Remove:
- patricia-cahill: Patricia stepped down as WG Comms Chair earlier this year. See https://github.com/cncf/tag-env-sustainability/pull/503
- xamebax & JacobValdemar: both lead a project which has been closed. See project archival issue https://github.com/cncf/tag-env-sustainability/issues/500 (see original tracking issue https://github.com/cncf/tag-env-sustainability/issues/347) 
Add:
- vallss: New WG Comms TL (see issue https://github.com/cncf/tag-env-sustainability/issues/520)
- locomundo: New WG Green Reviews TL (see issue: https://github.com/cncf/tag-env-sustainability/issues/513)
cc @RobertKielty
> Update tag env member list oct 2024

- people.json
Bio needs to be 20 characters or longer for the map popup window to display correctly.
> Update Sergej Alikov bio

- config.yaml
The end user repos are being restructured to more closely mirror the TOC.
A summary of changes:
- cncf/tab -> cncf/tab-private - used for private discussions, meetings etc
- cncf/enduser-public -> cncf/tab - used for public facing issues, policies, discussions, meetings
- cncf/enduser -> cncf/enduser-private - end user members only items, discussions etc
> Rename enduser and tab repos

- config.yaml
Admin access to update the GitHub action on `k8s-conformance` repo when there is a new verify-conformance version.
Fyi, @xmudrii @mfahlandt 
/cc @jeefy
> Add Kubermatic to k8s-conformance repo

- config.yaml
 - @melaniadeangelis - canceled her invitation
> Fix CLOWarden warnings

- people.json
I added my github and my slack id to get access to the private kubestronaut channel.
> Add slack and github to Florian Feldmann's profile

- people.json
My GitHub username was changed from `jholee` to `etamong`.
Previous related PR: https://github.com/cncf/people/pull/983
> Update Jooho Lee's github link in people.json
